config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#home'
  get  '/help',  to: 'static_pages#help'
  get  '/about', to: 'static_pages#about'
  get  '/contact', to:'static_pages#contact'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
    def Hello
      render html:"Hello World !"
    end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def help
  end

  def about
  end

  def contact
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
def full_title (page_title = '')
  base_title = "SIte de CHristian pour déconner !"
  if page_title.empty?
    base_title
  else
    page_title + "|" + base_title
  end
end

end

app/helpers/contact_helper.rb
module ContactHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    <a href="http://www.railstutorial.org/">Fait en Ruby on Rails</a>
    by <a href="https://www.facebook.com/christian.adou1?ref=bookmarks">Christian Merari</a>
  </small>
  <nav>
    <ul>
      <li><%= link_to "Home",   root_path %></li>
      <li><%= link_to "Contact", contact_path %></li>
      <li><a href="http://news.railstutorial.org/">News</a></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to "Mon site", root_path, id: "logo" %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Home",  root_path %></li>
        <li><%= link_to "Contact",   contact_path %></li>
        <li><%= link_to "Aide", help_path %></li>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/_shin.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all',
                                              'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  <%= render 'layouts/shin' %>
  </head>
  <body>
  <%= render 'layouts/header' %>
    <div class="container">
      <%= yield %>
      <%= render 'layouts/footer' %>
    </div>
  </body>
</html>

app/views/static_pages/about.html.erb
<%= provide(:title, "About") %>
    <h1>About</h1>
    <p>
      The <a href="http://www.railstutorial.org/"><em>Ruby on Rails
      Tutorial</em></a> is a
      <a href="http://www.railstutorial.org/book">book</a> and
      <a href="http://screencasts.railstutorial.org/">screencast series</a>
      to teach web development with
      <a href="http://rubyonrails.org/">Ruby on Rails</a>.
      This is the sample application for the tutorial.
    </p>

app/views/static_pages/contact.html.erb
<link href="https://fonts.googleapis.com/css?family=Oswald:700|Patua+One|Roboto+Condensed:700" rel="stylesheet">
<link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet">
<section id="contact" class="content-section text-center">
        <div class="contact-section">
            <div class="container">
              <h2>Djo Contact moi Oubien</h2>
              <p>Fait pas ta fiotte !! Ecris moi !</p>
              <div class="row">
                <div class="col-md-8 col-md-offset-2">
                  <form class="form-horizontal">
                    <div class="form-group">
                      <label for="exampleInputName2">Ton nom</label>
                      <input type="text" class="form-control" id="exampleInputName2" placeholder="Par exemple Christian">
                    </div>
                    <div class="form-group">
                      <label for="exampleInputEmail2">Ton Email</label>
                      <input type="email" class="form-control" id="exampleInputEmail2" placeholder="christian@example.com">
                    </div>
                    <div class="form-group ">
                      <label for="exampleInputText">Ouais tu veux dire quoi </label>
                     <textarea  class="form-control" placeholder="Description"></textarea>
                    </div>
                    <button type="submit" class="btn btn-default">Envoyer le message</button>
                  </form>

                  <hr>
                    <h3>Mes réseaux sociaux au cas ou tu veux me follow !</h3>
                  <ul class="list-inline banner-social-buttons">
                    <li><a href="https://twitter.com/ChrisMerari" class="btn btn-default btn-lg"><i class="fa fa-twitter"> <span class="network-name">Twitter</span></i></a></li>
                    <li><a href="https://www.facebook.com/christian.adou1" class="btn btn-default btn-lg"><i class="fa fa-facebook"> <span class="network-name">Facebook</span></i></a></li>
                    <li><a href="https://www.youtube.com/" class="btn btn-default btn-lg"><i class="fa fa-youtube-play"> <span class="network-name">Youtube</span></i></a></li>
                  </ul>
                </div>
              </div>
            </div>
        </div>
      </section>

app/views/static_pages/help.html.erb
<%= provide(:title, "Help") %>
    <h1>Aide</h1>
    <p>
  <h2>Djo la page est en construction !! Faut venir apres tchai !</h2> 
    </p>

app/views/static_pages/home.html.erb
<style >
body{
  background-image: url(https://images.unsplash.com/photo-1468465226960-8899e992537c?auto=format&fit=crop&w=1506&q=60&ixid=dW5zcGxhc2guY29tOzs7Ozs%3D);
  background-position: bottom;
}
</style>

<div class="center jumbotron">
  <h1>Bienvenue sur Mon Premier Site en Ruby on Rails</h1>

  <h2>
    Mon Premier Site en Ruby on Rails fait par
    <a href="https://www.facebook.com/christian.adou1?ref=bookmarks">Christian Merari</a>
  </h2>

  <%= link_to "Contactez moi ", contact_path, class: "btn btn-lg btn-primary" %>
</div>

<%= link_to image_tag("rails.png", alt: "Rails logo"),
            'http://rubyonrails.org/' %>